site_name: QGIS Learning Material
site_url: https://tars4815.github.io/qgis-learning-material/

# Configuration
theme:
  name: material
  palette:
    primary: green
  font:
    text: Open Sans
  language: en
  features:
    - navigation.path
    - navigation.footer
    - navigation.tabs
    - toc.integrate


# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fede_gaspari
    - icon: fontawesome/brands/github
      link: https://github.com/Tars4815
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/federicagaspari/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

repo_url: https://github.com/Tars4815/qgis-learning-material

plugins:
  - search
  - tags
  - git-authors
  - i18n:
      languages:
        - locale: en 
          name: English
          build: true
          default: true
        - locale: it
          name: Italiano
          build: true
          default: false
      nav_translations:
        it:
          Home: Home
          Courses: Corsi

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Page tree (language-neutral, i18n will pull from docs/en and docs/it)
nav:
  - Home: index.md
  - Courses:
      - Environmental Engineering: 
          - sit/sit-about.md
          - sit/sit-intro.md
          - sit/sit-qgis00.md
          - sit/sit-qgis01.md
      - Architecture:
          - arch/arch-pc-about.md
          - arch/arch-pc-intro.md
      - Urban Planning:
          - urb/about.md
          - urb/intro.md
          - urb/urb01.md
  - Workshop:
      - workshop/intro-workshop.md