site_name: QGIS Learning Material

theme:
  name: material
  palette:
    primary: green
  font:
    text: Open Sans
  language: it
  extra:
  consent:
    title: Cookie consent
    description: >- 


      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      
repo_url: https://github.com/Tars4815/qgis-learning-material

plugins:
  - i18n:
      languages:
        it: "Italiano"
        en: "English"
      default_language: 'en'
      no_translation:
        it: "Questa pagina non è tradotta in italiano."
        en: "This page isn't translated to English."


extra:
  # Default mkdocs-material alternate links for untranslated pages
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
  alternate:
    - name: English
      link: ""
      lang: en

    - name: Italiano
      link: index.it/
      lang: it




