site_name: QGIS Learning Material

# Configuration
theme:
  name: material
  palette:
    primary: green
  font:
    text: Open Sans
  language: en
  features:
    - navigation.path
    - navigation.footer

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/fede_gaspari
    - icon: fontawesome/brands/github
      link: https://github.com/Tars4815
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/federicagaspari/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

repo_url: https://github.com/Tars4815/qgis-learning-material

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        it:
          name: Italiano
          build: true
          default: false
        en:
          name: English
          build: true
          default: true
      no_translation:
        it: "Questa pagina non è tradotta in italiano."
        en: "This page isn't translated to English."


markdown_extensions:
  - attr_list

# Page tree
nav:
  - Home: index.md
  - Courses:
      - Sistemi Informativi Territoriali:
          - sit-intro.it.md
          - sit-qgis00.it.md
      - a. 2023:
          - Intro Workshop: intro-workshop.md
          - Sistemi Informativi Territoriali:
              - sit-about.md
              - sit-qgis00.md
              - sit-qgis01.md
              - sit-qgis02.md
      - a. 2022:
          - Piacenza Campus:
              - arch-pc-about.md
              - arch-pc-intro.md
              - arch-pc-layout.md
